services:
    db:
        image: postgres:latest
        ports:
        - "5432:5432"
        command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
            interval: 1s
            retries: 20
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        volumes:
        - database-data:/var/lib/postgresql/data
    
    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6380:6379"
        command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5
        volumes:
            - redis-data:/data
        restart: unless-stopped

    migrations:
        image: ghcr.io/kukymbr/goose-docker:3.24.2
        restart: no
        depends_on:
            db:
                condition: service_healthy
        environment:
        - GOOSE_DRIVER=postgres
        - GOOSE_DBSTRING=host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME}
        - GOOSE_VERBOSE=true
        - GOOSE_COMMAND=${GOOSE_COMMAND}
        - GOOSE_COMMAND_ARG=${GOOSE_COMMAND_ARG}
        volumes:
        - ./migrations:/migrations

    auth-service:
        build:
            context: ./backend/auth_service
        container_name: auth-service
        depends_on:
            migrations:
                condition: service_completed_successfully
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy
        ports:
        - "50051:50051"
        - "8084:8084"
        environment:
            CONFIG_PATH: /app/config/config.yml
        restart: unless-stopped
    

    frontend:
        build:
            context: ./frontend
        container_name: frontend
        ports:
            - "3000:80"
        depends_on:
            - auth-service
        restart: unless-stopped
    
    core-service:
        build:
            context: ./backend/core_service
        container_name: core-service
        depends_on:
            migrations:
                condition: service_completed_successfully
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy
        ports:
        - "8080:8080"
        environment:
            CONFIG_PATH: /app/config/config.yml
        restart: unless-stopped
    
    notifcation-service:
        build:
            context: ./backend/notification_service
        container_name: notifcation-service
        depends_on:
            migrations:
                condition: service_completed_successfully
            rabbitmq:
                condition: service_healthy
        ports:
        - "8082:8082"
        environment:
            CONFIG_PATH: /app/config/config.yml
        restart: unless-stopped

    booking-service:
        build:
            context: ./backend/booking_service
        container_name: booking-service
        depends_on:
            migrations:
                condition: service_completed_successfully
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy
        ports:
        - "8081:8081"
        environment:
            CONFIG_PATH: /app/config/config.yml
        restart: unless-stopped



    rabbitmq:
        image: rabbitmq:3.13.7-management
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
volumes:
    database-data:
    redis-data: