// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BookingStatus string

const (
	BookingStatusPending   BookingStatus = "pending"
	BookingStatusConfirmed BookingStatus = "confirmed"
	BookingStatusCompleted BookingStatus = "completed"
	BookingStatusCancelled BookingStatus = "cancelled"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type BusinessType string

const (
	BusinessTypeIP           BusinessType = "IP"
	BusinessTypeSelfEmployed BusinessType = "self_employed"
)

func (e *BusinessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessType(s)
	case string:
		*e = BusinessType(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessType: %T", src)
	}
	return nil
}

type NullBusinessType struct {
	BusinessType BusinessType `json:"business_type"`
	Valid        bool         `json:"valid"` // Valid is true if BusinessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessType) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessType), nil
}

type DiscoutnType string

const (
	DiscoutnTypePercentage  DiscoutnType = "percentage"
	DiscoutnTypeFixedAmount DiscoutnType = "fixed_amount"
)

func (e *DiscoutnType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscoutnType(s)
	case string:
		*e = DiscoutnType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscoutnType: %T", src)
	}
	return nil
}

type NullDiscoutnType struct {
	DiscoutnType DiscoutnType `json:"discoutn_type"`
	Valid        bool         `json:"valid"` // Valid is true if DiscoutnType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscoutnType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscoutnType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscoutnType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscoutnType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscoutnType), nil
}

type UserRole string

const (
	UserRoleAdmin     UserRole = "admin"
	UserRoleClient    UserRole = "client"
	UserRolePerformer UserRole = "performer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationStatus string

const (
	VerificationStatusPending  VerificationStatus = "pending"
	VerificationStatusVerified VerificationStatus = "verified"
	VerificationStatusRejected VerificationStatus = "rejected"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus `json:"verification_status"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type Booking struct {
	ID          uuid.UUID     `json:"id"`
	ClientID    uuid.UUID     `json:"client_id"`
	ServiceID   uuid.UUID     `json:"service_id"`
	BasePrice   int32         `json:"base_price"`
	DiscountID  uuid.NullUUID `json:"discount_id"`
	FinalPrice  int32         `json:"final_price"`
	BookingTime time.Time     `json:"booking_time"`
	Status      BookingStatus `json:"status"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type Discount struct {
	ID        uuid.UUID    `json:"id"`
	ServiceID uuid.UUID    `json:"service_id"`
	Type      DiscoutnType `json:"type"`
	Value     int32        `json:"value"`
	ValidFrom time.Time    `json:"valid_from"`
	ValidTo   time.Time    `json:"valid_to"`
	MaxUses   int32        `json:"max_uses"`
	UsedCount int32        `json:"used_count"`
	CreatedAt time.Time    `json:"created_at"`
}

type Review struct {
	ID        uuid.UUID      `json:"id"`
	BookingID uuid.UUID      `json:"booking_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Service struct {
	ID              uuid.UUID      `json:"id"`
	PerformerID     uuid.UUID      `json:"performer_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Price           int64          `json:"price"`
	DurationMinutes int32          `json:"duration_minutes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	PasswordHash       []byte             `json:"password_hash"`
	Role               UserRole           `json:"role"`
	Inn                sql.NullString     `json:"inn"`
	BusinessType       NullBusinessType   `json:"business_type"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}
