// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password_hash,
    role,
    inn,
    business_type,
    verification_status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, email, password_hash, role, inn, business_type, verification_status, created_at, updated_at
`

type CreateUserParams struct {
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               UserRole           `json:"role"`
	Inn                string             `json:"inn"`
	BusinessType       BusinessType       `json:"business_type"`
	VerificationStatus VerificationStatus `json:"verification_status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Inn,
		arg.BusinessType,
		arg.VerificationStatus,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Inn,
		&i.BusinessType,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, inn, business_type, verification_status, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Inn,
		&i.BusinessType,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
