// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAllBookings = `-- name: CountAllBookings :one
SELECT COUNT(*)
FROM bookings b
JOIN services s ON s.id = b.service_id
`

func (q *Queries) CountAllBookings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllBookings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllReviews = `-- name: CountAllReviews :one
SELECT COUNT(*)
FROM reviews r
JOIN bookings b ON b.id = r.booking_id
JOIN services s ON s.id = b.service_id
`

func (q *Queries) CountAllReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllServices = `-- name: CountAllServices :one
SELECT COUNT(*) FROM services
WHERE ($1::uuid IS NULL OR performer_id = $1)
`

func (q *Queries) CountAllServices(ctx context.Context, dollar_1 uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllServices, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnverifiedPerformers = `-- name: CountUnverifiedPerformers :one
SELECT COUNT(*) FROM users 
WHERE role = 'performer' AND verification_status = 'pending'
`

func (q *Queries) CountUnverifiedPerformers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnverifiedPerformers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithFilters = `-- name: CountUsersWithFilters :one
SELECT COUNT(*)
FROM users
`

func (q *Queries) CountUsersWithFilters(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersWithFilters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllBookings = `-- name: GetAllBookings :many
SELECT b.id, b.client_id, b.service_id, b.base_price, b.final_price, b.booking_time, b.status, b.created_at, b.updated_at,
       c.name as client_name, s.title as service_name
FROM bookings b
JOIN users c ON c.id = b.client_id
JOIN services s ON s.id = b.service_id
ORDER BY b.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllBookingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllBookingsRow struct {
	ID          uuid.UUID     `json:"id"`
	ClientID    uuid.UUID     `json:"client_id"`
	ServiceID   uuid.UUID     `json:"service_id"`
	BasePrice   int32         `json:"base_price"`
	FinalPrice  int32         `json:"final_price"`
	BookingTime time.Time     `json:"booking_time"`
	Status      BookingStatus `json:"status"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	ClientName  string        `json:"client_name"`
	ServiceName string        `json:"service_name"`
}

func (q *Queries) GetAllBookings(ctx context.Context, arg GetAllBookingsParams) ([]GetAllBookingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBookings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllBookingsRow{}
	for rows.Next() {
		var i GetAllBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.BasePrice,
			&i.FinalPrice,
			&i.BookingTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReviews = `-- name: GetAllReviews :many
SELECT r.id, r.booking_id, r.rating, r.comment, r.created_at, r.updated_at,
       u.name as client_name, s.id as service_id
FROM reviews r
JOIN bookings b ON b.id = r.booking_id
JOIN users u ON u.id = b.client_id
JOIN services s ON s.id = b.service_id
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllReviewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllReviewsRow struct {
	ID         uuid.UUID      `json:"id"`
	BookingID  uuid.UUID      `json:"booking_id"`
	Rating     int32          `json:"rating"`
	Comment    sql.NullString `json:"comment"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ClientName string         `json:"client_name"`
	ServiceID  uuid.UUID      `json:"service_id"`
}

func (q *Queries) GetAllReviews(ctx context.Context, arg GetAllReviewsParams) ([]GetAllReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllReviewsRow{}
	for rows.Next() {
		var i GetAllReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllServices = `-- name: GetAllServices :many
SELECT s.id, s.performer_id, s.title, s.description, s.price, s.duration_minutes, s.created_at, s.updated_at, u.name as performer_name
FROM services s
JOIN users u ON u.id = s.performer_id
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllServicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllServicesRow struct {
	ID              uuid.UUID      `json:"id"`
	PerformerID     uuid.UUID      `json:"performer_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Price           int64          `json:"price"`
	DurationMinutes int32          `json:"duration_minutes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	PerformerName   string         `json:"performer_name"`
}

func (q *Queries) GetAllServices(ctx context.Context, arg GetAllServicesParams) ([]GetAllServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllServicesRow{}
	for rows.Next() {
		var i GetAllServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.PerformerID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PerformerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnverifiedPerformers = `-- name: GetUnverifiedPerformers :many
SELECT 
    u.id, u.name, u.email, u.inn, u.business_type, u.verification_status, 
    u.role, u.created_at, u.updated_at,
    COUNT(DISTINCT s.id) as services_count,
    COUNT(DISTINCT b.id) as total_bookings
FROM users u
LEFT JOIN services s ON s.performer_id = u.id
LEFT JOIN bookings b ON b.service_id = s.id
WHERE u.role = 'performer' AND u.verification_status = 'pending'
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type GetUnverifiedPerformersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUnverifiedPerformersRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Inn                sql.NullString     `json:"inn"`
	BusinessType       NullBusinessType   `json:"business_type"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	Role               UserRole           `json:"role"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	ServicesCount      int64              `json:"services_count"`
	TotalBookings      int64              `json:"total_bookings"`
}

func (q *Queries) GetUnverifiedPerformers(ctx context.Context, arg GetUnverifiedPerformersParams) ([]GetUnverifiedPerformersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnverifiedPerformers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnverifiedPerformersRow{}
	for rows.Next() {
		var i GetUnverifiedPerformersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Inn,
			&i.BusinessType,
			&i.VerificationStatus,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServicesCount,
			&i.TotalBookings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, inn, business_type, role, verification_status, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Inn                sql.NullString     `json:"inn"`
	BusinessType       NullBusinessType   `json:"business_type"`
	Role               UserRole           `json:"role"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Inn,
		&i.BusinessType,
		&i.Role,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersWithFilters = `-- name: GetUsersWithFilters :many
SELECT id, name, email, inn, business_type, role, verification_status, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetUsersWithFiltersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUsersWithFiltersRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Inn                sql.NullString     `json:"inn"`
	BusinessType       NullBusinessType   `json:"business_type"`
	Role               UserRole           `json:"role"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

func (q *Queries) GetUsersWithFilters(ctx context.Context, arg GetUsersWithFiltersParams) ([]GetUsersWithFiltersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithFilters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithFiltersRow{}
	for rows.Next() {
		var i GetUsersWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Inn,
			&i.BusinessType,
			&i.Role,
			&i.VerificationStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateVerificationStatus = `-- name: UpdateVerificationStatus :exec
UPDATE users SET verification_status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateVerificationStatusParams struct {
	ID                 uuid.UUID          `json:"id"`
	VerificationStatus VerificationStatus `json:"verification_status"`
}

func (q *Queries) UpdateVerificationStatus(ctx context.Context, arg UpdateVerificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVerificationStatus, arg.ID, arg.VerificationStatus)
	return err
}
