// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discounts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDiscount = `-- name: CreateDiscount :one
INSERT INTO discounts (service_id, type, value, valid_from, valid_to, max_uses, used_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, service_id, type, value, valid_from, valid_to, max_uses, used_count, created_at
`

type CreateDiscountParams struct {
	ServiceID uuid.UUID    `json:"service_id"`
	Type      DiscoutnType `json:"type"`
	Value     int32        `json:"value"`
	ValidFrom time.Time    `json:"valid_from"`
	ValidTo   time.Time    `json:"valid_to"`
	MaxUses   int32        `json:"max_uses"`
	UsedCount int32        `json:"used_count"`
}

func (q *Queries) CreateDiscount(ctx context.Context, arg CreateDiscountParams) (Discount, error) {
	row := q.db.QueryRowContext(ctx, createDiscount,
		arg.ServiceID,
		arg.Type,
		arg.Value,
		arg.ValidFrom,
		arg.ValidTo,
		arg.MaxUses,
		arg.UsedCount,
	)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Type,
		&i.Value,
		&i.ValidFrom,
		&i.ValidTo,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDiscount = `-- name: DeleteDiscount :exec
DELETE FROM discounts WHERE id = $1
`

func (q *Queries) DeleteDiscount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDiscount, id)
	return err
}

const getDiscountById = `-- name: GetDiscountById :one
SELECT id, service_id, type, value, valid_from, valid_to, max_uses, used_count, created_at FROM discounts WHERE id = $1
`

func (q *Queries) GetDiscountById(ctx context.Context, id uuid.UUID) (Discount, error) {
	row := q.db.QueryRowContext(ctx, getDiscountById, id)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Type,
		&i.Value,
		&i.ValidFrom,
		&i.ValidTo,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedAt,
	)
	return i, err
}

const getDiscountsByServiceID = `-- name: GetDiscountsByServiceID :many
SELECT id, service_id, type, value, valid_from, valid_to, max_uses, used_count, created_at FROM discounts 
WHERE service_id = $1 
  AND valid_from <= NOW() 
  AND valid_to >= NOW()
  AND used_count < max_uses
ORDER BY created_at DESC
`

func (q *Queries) GetDiscountsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]Discount, error) {
	rows, err := q.db.QueryContext(ctx, getDiscountsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Discount{}
	for rows.Next() {
		var i Discount
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Type,
			&i.Value,
			&i.ValidFrom,
			&i.ValidTo,
			&i.MaxUses,
			&i.UsedCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscount = `-- name: UpdateDiscount :exec
UPDATE discounts
SET
    valid_from = COALESCE($2, valid_from),
    valid_to = COALESCE($3, valid_to),
    max_uses = COALESCE($4, max_uses)
WHERE id = $1
`

type UpdateDiscountParams struct {
	ID        uuid.UUID `json:"id"`
	ValidFrom time.Time `json:"valid_from"`
	ValidTo   time.Time `json:"valid_to"`
	MaxUses   int32     `json:"max_uses"`
}

func (q *Queries) UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) error {
	_, err := q.db.ExecContext(ctx, updateDiscount,
		arg.ID,
		arg.ValidFrom,
		arg.ValidTo,
		arg.MaxUses,
	)
	return err
}
