// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusPending   BookingStatus = "pending"
	BookingStatusConfirmed BookingStatus = "confirmed"
	BookingStatusCompleted BookingStatus = "completed"
	BookingStatusCancelled BookingStatus = "cancelled"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type BusinessType string

const (
	BusinessTypeIP           BusinessType = "IP"
	BusinessTypeSelfEmployed BusinessType = "self_employed"
)

func (e *BusinessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessType(s)
	case string:
		*e = BusinessType(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessType: %T", src)
	}
	return nil
}

type NullBusinessType struct {
	BusinessType BusinessType `json:"business_type"`
	Valid        bool         `json:"valid"` // Valid is true if BusinessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessType) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessType), nil
}

type DiscoutnType string

const (
	DiscoutnTypePercentage  DiscoutnType = "percentage"
	DiscoutnTypeFixedAmount DiscoutnType = "fixed_amount"
)

func (e *DiscoutnType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscoutnType(s)
	case string:
		*e = DiscoutnType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscoutnType: %T", src)
	}
	return nil
}

type NullDiscoutnType struct {
	DiscoutnType DiscoutnType `json:"discoutn_type"`
	Valid        bool         `json:"valid"` // Valid is true if DiscoutnType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscoutnType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscoutnType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscoutnType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscoutnType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscoutnType), nil
}

type UserRole string

const (
	UserRoleAdmin     UserRole = "admin"
	UserRoleClient    UserRole = "client"
	UserRolePerformer UserRole = "performer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationStatus string

const (
	VerificationStatusPending  VerificationStatus = "pending"
	VerificationStatusVerified VerificationStatus = "verified"
	VerificationStatusRejected VerificationStatus = "rejected"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus `json:"verification_status"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type Booking struct {
	ID             pgtype.UUID        `json:"id"`
	ClientID       pgtype.UUID        `json:"client_id"`
	ServiceID      pgtype.UUID        `json:"service_id"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	FinalPrice     pgtype.Numeric     `json:"final_price"`
	BookingTime    pgtype.Timestamptz `json:"booking_time"`
	Status         BookingStatus      `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Discount struct {
	ID        pgtype.UUID        `json:"id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	Type      DiscoutnType       `json:"type"`
	Value     pgtype.Numeric     `json:"value"`
	ValidFrom pgtype.Timestamptz `json:"valid_from"`
	ValidTo   pgtype.Timestamptz `json:"valid_to"`
	MaxUses   int32              `json:"max_uses"`
	UsedCount int32              `json:"used_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID        pgtype.UUID        `json:"id"`
	BookingID pgtype.UUID        `json:"booking_id"`
	Rating    int32              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID              pgtype.UUID        `json:"id"`
	PerformerID     pgtype.UUID        `json:"performer_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Price           pgtype.Numeric     `json:"price"`
	DurationMinutes int32              `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               UserRole           `json:"role"`
	Inn                string             `json:"inn"`
	BusinessType       BusinessType       `json:"business_type"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
