// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getProfile = `-- name: GetProfile :one
SELECT 
    u.name,
    u.email,
    u.role,
    u.inn,
    u.business_type,
    u.verification_status 
FROM users u
WHERE u.id = $1
`

type GetProfileRow struct {
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Role               UserRole           `json:"role"`
	Inn                string             `json:"inn"`
	BusinessType       BusinessType       `json:"business_type"`
	VerificationStatus VerificationStatus `json:"verification_status"`
}

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Inn,
		&i.BusinessType,
		&i.VerificationStatus,
	)
	return i, err
}
