// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT 
    u.name,
    u.email,
    u.role,
    u.inn,
    u.business_type,
    u.verification_status 
FROM users u
WHERE u.id = $1
`

type GetProfileRow struct {
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Role               UserRole           `json:"role"`
	Inn                sql.NullString     `json:"inn"`
	BusinessType       BusinessType       `json:"business_type"`
	VerificationStatus VerificationStatus `json:"verification_status"`
}

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Inn,
		&i.BusinessType,
		&i.VerificationStatus,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE users 
SET email = $1, name = $2
WHERE id = $3
`

type UpdateProfileParams struct {
	Email string    `json:"email"`
	Name  string    `json:"name"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile, arg.Email, arg.Name, arg.ID)
	return err
}
