// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	DeleteProfile(ctx context.Context, id uuid.UUID) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	ListServices(ctx context.Context) ([]Service, error)
	SearchServices(ctx context.Context, arg SearchServicesParams) ([]Service, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) error
}

var _ Querier = (*Queries)(nil)
