// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	ListServices(ctx context.Context) ([]Service, error)
}

var _ Querier = (*Queries)(nil)
