// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAllBookings(ctx context.Context) (int64, error)
	CountAllReviews(ctx context.Context) (int64, error)
	CountAllServices(ctx context.Context) (int64, error)
	CountUnverifiedPerformers(ctx context.Context) (int64, error)
	CountUsersWithFilters(ctx context.Context) (int64, error)
	CreateDiscount(ctx context.Context, arg CreateDiscountParams) (Discount, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	DeleteDiscount(ctx context.Context, id uuid.UUID) error
	DeleteProfile(ctx context.Context, id uuid.UUID) error
	DeleteReview(ctx context.Context, id uuid.UUID) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllBookings(ctx context.Context, arg GetAllBookingsParams) ([]GetAllBookingsRow, error)
	GetAllReviews(ctx context.Context, arg GetAllReviewsParams) ([]GetAllReviewsRow, error)
	GetAllServices(ctx context.Context, arg GetAllServicesParams) ([]GetAllServicesRow, error)
	GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error)
	GetDiscountById(ctx context.Context, id uuid.UUID) (Discount, error)
	GetDiscountsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]Discount, error)
	GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error)
	GetReviewByBookingID(ctx context.Context, bookingID uuid.UUID) (Review, error)
	GetReviewByID(ctx context.Context, id uuid.UUID) (Review, error)
	GetReviewsByServiceID(ctx context.Context, arg GetReviewsByServiceIDParams) ([]Review, error)
	GetService(ctx context.Context, id uuid.UUID) (GetServiceRow, error)
	GetServices(ctx context.Context, performerID uuid.UUID) ([]Service, error)
	GetUnverifiedPerformers(ctx context.Context, arg GetUnverifiedPerformersParams) ([]GetUnverifiedPerformersRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUsersWithFilters(ctx context.Context, arg GetUsersWithFiltersParams) ([]GetUsersWithFiltersRow, error)
	ListServices(ctx context.Context) ([]Service, error)
	SearchServices(ctx context.Context, arg SearchServicesParams) ([]Service, error)
	UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateProfileVerificationStatus(ctx context.Context, arg UpdateProfileVerificationStatusParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateVerificationStatus(ctx context.Context, arg UpdateVerificationStatusParams) error
}

var _ Querier = (*Queries)(nil)
