// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (booking_id, rating, comment)
VALUES ($1, $2, $3)
RETURNING id, booking_id, rating, comment, created_at, updated_at
`

type CreateReviewParams struct {
	BookingID uuid.UUID      `json:"booking_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview, arg.BookingID, arg.Rating, arg.Comment)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT b.id, b.client_id, b.service_id, b.base_price, b.discount_id, b.final_price, b.booking_time, b.status, b.created_at, b.updated_at, s.title AS service_title, s.performer_id, d.type AS discount_type, d.value AS discount_value
FROM bookings b
JOIN services s ON b.service_id = s.id
LEFT JOIN discounts d ON b.discount_id = d.id
WHERE b.id = $1
`

type GetBookingByIDRow struct {
	ID            uuid.UUID        `json:"id"`
	ClientID      uuid.UUID        `json:"client_id"`
	ServiceID     uuid.UUID        `json:"service_id"`
	BasePrice     int32            `json:"base_price"`
	DiscountID    uuid.NullUUID    `json:"discount_id"`
	FinalPrice    int32            `json:"final_price"`
	BookingTime   time.Time        `json:"booking_time"`
	Status        BookingStatus    `json:"status"`
	CreatedAt     time.Time        `json:"created_at"`
	UpdatedAt     time.Time        `json:"updated_at"`
	ServiceTitle  string           `json:"service_title"`
	PerformerID   uuid.UUID        `json:"performer_id"`
	DiscountType  NullDiscoutnType `json:"discount_type"`
	DiscountValue sql.NullInt32    `json:"discount_value"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.BasePrice,
		&i.DiscountID,
		&i.FinalPrice,
		&i.BookingTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceTitle,
		&i.PerformerID,
		&i.DiscountType,
		&i.DiscountValue,
	)
	return i, err
}

const getReviewByBookingID = `-- name: GetReviewByBookingID :one
SELECT id, booking_id, rating, comment, created_at, updated_at FROM reviews WHERE booking_id = $1
`

func (q *Queries) GetReviewByBookingID(ctx context.Context, bookingID uuid.UUID) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByBookingID, bookingID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, booking_id, rating, comment, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewsByServiceID = `-- name: GetReviewsByServiceID :many
SELECT r.id, r.booking_id, r.rating, r.comment, r.created_at, r.updated_at
FROM reviews r
JOIN bookings b ON r.booking_id = b.id
WHERE b.service_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type GetReviewsByServiceIDParams struct {
	ServiceID uuid.UUID `json:"service_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetReviewsByServiceID(ctx context.Context, arg GetReviewsByServiceIDParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsByServiceID, arg.ServiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews
SET rating = $2, comment = $3
WHERE id = $1
`

type UpdateReviewParams struct {
	ID      uuid.UUID      `json:"id"`
	Rating  int32          `json:"rating"`
	Comment sql.NullString `json:"comment"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview, arg.ID, arg.Rating, arg.Comment)
	return err
}
