// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    performer_id, title, description, price, duration_minutes
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, performer_id, title, description, price, duration_minutes, created_at, updated_at
`

type CreateServiceParams struct {
	PerformerID     uuid.UUID      `json:"performer_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Price           string         `json:"price"`
	DurationMinutes int32          `json:"duration_minutes"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.PerformerID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.DurationMinutes,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.PerformerID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, performer_id, title, description, price, duration_minutes, created_at, updated_at FROM services
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.PerformerID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
