// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelBooking, id)
	return err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    client_id,
    service_id,
    base_price,
    discount_id,
    final_price,
    booking_time,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id
`

type CreateBookingParams struct {
	ClientID    uuid.UUID     `json:"client_id"`
	ServiceID   uuid.UUID     `json:"service_id"`
	BasePrice   int32         `json:"base_price"`
	DiscountID  uuid.NullUUID `json:"discount_id"`
	FinalPrice  int32         `json:"final_price"`
	BookingTime time.Time     `json:"booking_time"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.ClientID,
		arg.ServiceID,
		arg.BasePrice,
		arg.DiscountID,
		arg.FinalPrice,
		arg.BookingTime,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, client_id, service_id, base_price, discount_id, final_price, booking_time, status, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.BasePrice,
		&i.DiscountID,
		&i.FinalPrice,
		&i.BookingTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT b.id, b.client_id, b.service_id, b.base_price, b.discount_id, b.final_price, b.booking_time, b.status, b.created_at, b.updated_at, s.title AS service_title, s.performer_id, d.type AS discount_type, d.value AS discount_value
FROM bookings b
JOIN services s ON b.service_id = s.id
LEFT JOIN discounts d ON b.discount_id = d.id
WHERE b.id = $1
`

type GetBookingByIDRow struct {
	ID            uuid.UUID        `json:"id"`
	ClientID      uuid.UUID        `json:"client_id"`
	ServiceID     uuid.UUID        `json:"service_id"`
	BasePrice     int32            `json:"base_price"`
	DiscountID    uuid.NullUUID    `json:"discount_id"`
	FinalPrice    int32            `json:"final_price"`
	BookingTime   time.Time        `json:"booking_time"`
	Status        BookingStatus    `json:"status"`
	CreatedAt     time.Time        `json:"created_at"`
	UpdatedAt     time.Time        `json:"updated_at"`
	ServiceTitle  string           `json:"service_title"`
	PerformerID   uuid.UUID        `json:"performer_id"`
	DiscountType  NullDiscoutnType `json:"discount_type"`
	DiscountValue sql.NullInt32    `json:"discount_value"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.BasePrice,
		&i.DiscountID,
		&i.FinalPrice,
		&i.BookingTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceTitle,
		&i.PerformerID,
		&i.DiscountType,
		&i.DiscountValue,
	)
	return i, err
}

const getBookingsForUpdate = `-- name: GetBookingsForUpdate :many
SELECT b.id, b.booking_time, s.duration_minutes from bookings b
JOIN services s ON s.id = b.service_id
WHERE b.service_id = $1 AND b.status IN ('pending', 'confirmed')
FOR UPDATE
`

type GetBookingsForUpdateRow struct {
	ID              uuid.UUID `json:"id"`
	BookingTime     time.Time `json:"booking_time"`
	DurationMinutes int32     `json:"duration_minutes"`
}

func (q *Queries) GetBookingsForUpdate(ctx context.Context, serviceID uuid.UUID) ([]GetBookingsForUpdateRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookingsForUpdate, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingsForUpdateRow{}
	for rows.Next() {
		var i GetBookingsForUpdateRow
		if err := rows.Scan(&i.ID, &i.BookingTime, &i.DurationMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountById = `-- name: GetDiscountById :one
SELECT id, service_id, type, value, valid_from, valid_to, max_uses, used_count, created_at FROM discounts WHERE id = $1
`

func (q *Queries) GetDiscountById(ctx context.Context, id uuid.UUID) (Discount, error) {
	row := q.db.QueryRowContext(ctx, getDiscountById, id)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Type,
		&i.Value,
		&i.ValidFrom,
		&i.ValidTo,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceById = `-- name: GetServiceById :one
SELECT id, performer_id, title, description, price, duration_minutes, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceById(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceById, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.PerformerID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, password_hash, role, inn, business_type, verification_status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Inn,
		&i.BusinessType,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitBooking = `-- name: SubmitBooking :exec
UPDATE bookings
SET status = 'confirmed', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SubmitBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, submitBooking, id)
	return err
}
