// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelBooking, id)
	return err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    client_id,
    service_id,
    base_price,
    discount_id,
    final_price,
    booking_time,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id
`

type CreateBookingParams struct {
	ClientID    uuid.UUID     `json:"client_id"`
	ServiceID   uuid.UUID     `json:"service_id"`
	BasePrice   int32         `json:"base_price"`
	DiscountID  uuid.NullUUID `json:"discount_id"`
	FinalPrice  int32         `json:"final_price"`
	BookingTime time.Time     `json:"booking_time"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.ClientID,
		arg.ServiceID,
		arg.BasePrice,
		arg.DiscountID,
		arg.FinalPrice,
		arg.BookingTime,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getBooking = `-- name: GetBooking :one
SELECT id, client_id, service_id, base_price, discount_id, final_price, booking_time, status, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.BasePrice,
		&i.DiscountID,
		&i.FinalPrice,
		&i.BookingTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByClientID = `-- name: GetBookingByClientID :many
SELECT id, client_id, service_id, base_price, discount_id, final_price, booking_time, status, created_at, updated_at FROM bookings WHERE client_id = $1
`

func (q *Queries) GetBookingByClientID(ctx context.Context, clientID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, getBookingByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.BasePrice,
			&i.DiscountID,
			&i.FinalPrice,
			&i.BookingTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT b.id, b.client_id, b.service_id, b.base_price, b.discount_id, b.final_price, b.booking_time, b.status, b.created_at, b.updated_at, s.title AS service_title, s.performer_id, d.type AS discount_type, d.value AS discount_value
FROM bookings b
JOIN services s ON b.service_id = s.id
LEFT JOIN discounts d ON b.discount_id = d.id
WHERE b.id = $1
`

type GetBookingByIDRow struct {
	ID            uuid.UUID        `json:"id"`
	ClientID      uuid.UUID        `json:"client_id"`
	ServiceID     uuid.UUID        `json:"service_id"`
	BasePrice     int32            `json:"base_price"`
	DiscountID    uuid.NullUUID    `json:"discount_id"`
	FinalPrice    int32            `json:"final_price"`
	BookingTime   time.Time        `json:"booking_time"`
	Status        BookingStatus    `json:"status"`
	CreatedAt     time.Time        `json:"created_at"`
	UpdatedAt     time.Time        `json:"updated_at"`
	ServiceTitle  string           `json:"service_title"`
	PerformerID   uuid.UUID        `json:"performer_id"`
	DiscountType  NullDiscoutnType `json:"discount_type"`
	DiscountValue sql.NullInt32    `json:"discount_value"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ServiceID,
		&i.BasePrice,
		&i.DiscountID,
		&i.FinalPrice,
		&i.BookingTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceTitle,
		&i.PerformerID,
		&i.DiscountType,
		&i.DiscountValue,
	)
	return i, err
}

const getBookingByPerformerID = `-- name: GetBookingByPerformerID :many
SELECT b.id, b.client_id, b.service_id, b.base_price, b.discount_id, b.final_price, b.booking_time, b.status, b.created_at, b.updated_at FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE s.performer_id = $1
`

func (q *Queries) GetBookingByPerformerID(ctx context.Context, performerID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, getBookingByPerformerID, performerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.BasePrice,
			&i.DiscountID,
			&i.FinalPrice,
			&i.BookingTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByPerformerWithServiceInfo = `-- name: GetBookingsByPerformerWithServiceInfo :many
SELECT 
    b.id, b.client_id, b.service_id, b.base_price, b.discount_id, b.final_price, b.booking_time, b.status, b.created_at, b.updated_at,
    s.title AS service_title
FROM bookings b
JOIN services s ON b.service_id = s.id
WHERE s.performer_id = $1
ORDER BY b.booking_time DESC
`

type GetBookingsByPerformerWithServiceInfoRow struct {
	ID           uuid.UUID     `json:"id"`
	ClientID     uuid.UUID     `json:"client_id"`
	ServiceID    uuid.UUID     `json:"service_id"`
	BasePrice    int32         `json:"base_price"`
	DiscountID   uuid.NullUUID `json:"discount_id"`
	FinalPrice   int32         `json:"final_price"`
	BookingTime  time.Time     `json:"booking_time"`
	Status       BookingStatus `json:"status"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
	ServiceTitle string        `json:"service_title"`
}

func (q *Queries) GetBookingsByPerformerWithServiceInfo(ctx context.Context, performerID uuid.UUID) ([]GetBookingsByPerformerWithServiceInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookingsByPerformerWithServiceInfo, performerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingsByPerformerWithServiceInfoRow{}
	for rows.Next() {
		var i GetBookingsByPerformerWithServiceInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.BasePrice,
			&i.DiscountID,
			&i.FinalPrice,
			&i.BookingTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsForUpdate = `-- name: GetBookingsForUpdate :many
SELECT 
    b.id,
    b.booking_time,
    s.duration_minutes
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE s.performer_id = $1
  AND b.status IN ('pending', 'confirmed')
  AND b.booking_time < $3
  AND b.booking_time + (s.duration_minutes || ' minutes')::interval > $2  -- new_start
FOR UPDATE
`

type GetBookingsForUpdateParams struct {
	PerformerID   uuid.UUID `json:"performer_id"`
	BookingTime   time.Time `json:"booking_time"`
	BookingTime_2 time.Time `json:"booking_time_2"`
}

type GetBookingsForUpdateRow struct {
	ID              uuid.UUID `json:"id"`
	BookingTime     time.Time `json:"booking_time"`
	DurationMinutes int32     `json:"duration_minutes"`
}

func (q *Queries) GetBookingsForUpdate(ctx context.Context, arg GetBookingsForUpdateParams) ([]GetBookingsForUpdateRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookingsForUpdate, arg.PerformerID, arg.BookingTime, arg.BookingTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingsForUpdateRow{}
	for rows.Next() {
		var i GetBookingsForUpdateRow
		if err := rows.Scan(&i.ID, &i.BookingTime, &i.DurationMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsWithServiceInfo = `-- name: GetBookingsWithServiceInfo :many
SELECT 
    b.id, b.client_id, b.service_id, b.base_price, b.discount_id, b.final_price, b.booking_time, b.status, b.created_at, b.updated_at,
    s.title AS service_title,
    s.performer_id
FROM bookings b
JOIN services s ON b.service_id = s.id
WHERE b.client_id = $1
ORDER BY b.booking_time DESC
`

type GetBookingsWithServiceInfoRow struct {
	ID           uuid.UUID     `json:"id"`
	ClientID     uuid.UUID     `json:"client_id"`
	ServiceID    uuid.UUID     `json:"service_id"`
	BasePrice    int32         `json:"base_price"`
	DiscountID   uuid.NullUUID `json:"discount_id"`
	FinalPrice   int32         `json:"final_price"`
	BookingTime  time.Time     `json:"booking_time"`
	Status       BookingStatus `json:"status"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
	ServiceTitle string        `json:"service_title"`
	PerformerID  uuid.UUID     `json:"performer_id"`
}

func (q *Queries) GetBookingsWithServiceInfo(ctx context.Context, clientID uuid.UUID) ([]GetBookingsWithServiceInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookingsWithServiceInfo, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingsWithServiceInfoRow{}
	for rows.Next() {
		var i GetBookingsWithServiceInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ServiceID,
			&i.BasePrice,
			&i.DiscountID,
			&i.FinalPrice,
			&i.BookingTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceTitle,
			&i.PerformerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscountById = `-- name: GetDiscountById :one
SELECT id, service_id, type, value, valid_from, valid_to, max_uses, used_count, created_at FROM discounts WHERE id = $1
`

func (q *Queries) GetDiscountById(ctx context.Context, id uuid.UUID) (Discount, error) {
	row := q.db.QueryRowContext(ctx, getDiscountById, id)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Type,
		&i.Value,
		&i.ValidFrom,
		&i.ValidTo,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceById = `-- name: GetServiceById :one
SELECT id, performer_id, title, description, price, duration_minutes, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceById(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceById, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.PerformerID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, password_hash, role, inn, business_type, verification_status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Inn,
		&i.BusinessType,
		&i.VerificationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const increaseDiscountUsage = `-- name: IncreaseDiscountUsage :exec
UPDATE discounts
SET used_count = used_count + 1
WHERE id = $1
`

func (q *Queries) IncreaseDiscountUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, increaseDiscountUsage, id)
	return err
}

const serviceExists = `-- name: ServiceExists :one
SELECT EXISTS (SELECT id, performer_id, title, description, price, duration_minutes, created_at, updated_at FROM services WHERE id = $1)
`

func (q *Queries) ServiceExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, serviceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const submitBooking = `-- name: SubmitBooking :exec
UPDATE bookings
SET status = 'confirmed', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SubmitBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, submitBooking, id)
	return err
}

const updateBookingTime1 = `-- name: UpdateBookingTime1 :exec
UPDATE bookings
SET booking_time = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateBookingTime1Params struct {
	BookingTime time.Time `json:"booking_time"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBookingTime1(ctx context.Context, arg UpdateBookingTime1Params) error {
	_, err := q.db.ExecContext(ctx, updateBookingTime1, arg.BookingTime, arg.ID)
	return err
}

const updateBookingTime2 = `-- name: UpdateBookingTime2 :exec
UPDATE bookings
SET booking_time = $1,
    status = 'pending',
    updated_at = NOW()
WHERE id = $2
`

type UpdateBookingTime2Params struct {
	BookingTime time.Time `json:"booking_time"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBookingTime2(ctx context.Context, arg UpdateBookingTime2Params) error {
	_, err := q.db.ExecContext(ctx, updateBookingTime2, arg.BookingTime, arg.ID)
	return err
}
