// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CancelBooking(ctx context.Context, id uuid.UUID) error
	CompletedBooking(ctx context.Context, id uuid.UUID) error
	CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error)
	DeleteBooking(ctx context.Context, id uuid.UUID) error
	GetBooking(ctx context.Context, id uuid.UUID) (Booking, error)
	GetBookingByClientID(ctx context.Context, clientID uuid.UUID) ([]Booking, error)
	GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error)
	GetBookingByPerformerID(ctx context.Context, performerID uuid.UUID) ([]Booking, error)
	GetBookingsByPerformerWithServiceInfo(ctx context.Context, performerID uuid.UUID) ([]GetBookingsByPerformerWithServiceInfoRow, error)
	GetBookingsForUpdate(ctx context.Context, arg GetBookingsForUpdateParams) ([]GetBookingsForUpdateRow, error)
	GetBookingsWithServiceInfo(ctx context.Context, clientID uuid.UUID) ([]GetBookingsWithServiceInfoRow, error)
	GetDiscountById(ctx context.Context, id uuid.UUID) (Discount, error)
	GetServiceById(ctx context.Context, id uuid.UUID) (Service, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	IncreaseDiscountUsage(ctx context.Context, id uuid.UUID) error
	ServiceExists(ctx context.Context, id uuid.UUID) (bool, error)
	SubmitBooking(ctx context.Context, id uuid.UUID) error
	UpdateBookingTime1(ctx context.Context, arg UpdateBookingTime1Params) error
	UpdateBookingTime2(ctx context.Context, arg UpdateBookingTime2Params) error
}

var _ Querier = (*Queries)(nil)
