// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CancelBooking(ctx context.Context, id uuid.UUID) error
	CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error)
	GetBooking(ctx context.Context, id uuid.UUID) (Booking, error)
	GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error)
	GetBookingsForUpdate(ctx context.Context, serviceID uuid.UUID) ([]GetBookingsForUpdateRow, error)
	GetDiscountById(ctx context.Context, id uuid.UUID) (Discount, error)
	GetServiceById(ctx context.Context, id uuid.UUID) (Service, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	SubmitBooking(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
